.TH KRUBYAPPLICATION "1" "July 2008" "Korundum version 4.1" 
.SH NAME
krubyapplication \- a KDE ruby application loader

.SH SYNOPSIS
.B krubyapplication 
application_directory/ruby_script
[Qt-options]
[KDE-options]

.SH DESCRIPTION

.B krubyapplication
Allows KDE ruby applications to be launched via a
.B .desktop
file.

.SH AUTHOR
.B krubyapplication
was written by Richard Dale.

This manual page was written by David Palacio for the Debian
project, but may be used by others. 
