.TH RBKCONFIG_COMPILER4 "1" "July 2008" "KDE4 version 4.1" 
.SH NAME
rbkconfig_compiler4 \- KDE config resource compiler

.SH SYNOPSIS
.B rbkconfig_compiler4
[options]
.I inputs
file.kcfg
file.kcfgc

.SH DESCRIPTION

.B rbkconfig_compiler4
compiles KDE config resources into ruby code.

.SH OPTIONS
.TP
.BI -L, --license
Displays software license
.TP
.BI -d, --directory <directory>
Directory to generate files in. By default it is set to the current directory.
.TP
.BI -h, --help
Display option summary

.SH AUTHOR
.B rbkconfig_compiler4
was written by Copyright 2003 Cornelius Schumacher, Waldo Bastian, Zack Rusin,
Reinhold Kainhofer, Duncan Mac-Vicar P., Harald Fernengel and Richard Dale.

This manual page was written by David
Palacio for the Debian project, but may be used by others.
